### ISSUE TITLE
about example

### ISSUE THREAD

**Issue by cosnis** [aisthesis/pynance#10]
hi, can u make some example code to show how made a great photo to show?

can't quickly know how use this library, T_T

but i think this is a great library and i want use it, thanks for your work.

**Comment by aisthesis** [comment]
There are a lot of examples in the documentation at http://pynance.net/ Could you explain more about what you're wanting if that isn't enough?

**Comment by cosnis** [comment]
http://matplotlib.org/examples/pylab_examples/

like that, full example, don't just show a part.
