### ISSUE TITLE
Saving pynance plots

### ISSUE THREAD

**Issue by datamodeler** [aisthesis/pynance#11]
how can I sane my pynance plots  to a pdf?

how can I set the colors?

Thanks

**Comment by aisthesis** [comment]
`pynance 0.5.0` will have an example of how to save your plot. There is no option for setting colors. To do that, you will have to build the plot using `matplotlib`. The idea here is to make it very easy to get a basic chart for validation purposes. As soon as you start supporting a lot of options, the functions become more complex and harder to use.

If colors are important to you, please provide a function signature that would fit easily with current functionality while supporting custom colors.
