### ISSUE TITLE
Default end date for data retrieval

### ISSUE THREAD

**Issue by aisthesis** [aisthesis/pynance#6]
For `pn.data.get()` use a default end date that will retrieve all data until now.

**Comment by arkadasgupta** [comment]
have you fixed this?

**Comment by arkadasgupta** [comment]
if not, i will work on this over the weekend. or maybe you can recommend one.

**Comment by aisthesis** [comment]
not fixed. Sounds like a good choice.

**Comment by aisthesis** [comment]
Closed with https://github.com/aisthesis/pynance/commit/2b8f69fbac747484b6d8a718cab5b2ab1af2ccd4
